### ISSUE TITLE
Cannot access account every ten minutes or so

### ISSUE THREAD

**Issue by BBEHannes** [irritanterik/homey-tesla.com#40]
Lately I have been having problems with my connection to the car. After restarting the app, it can successfully connect to the car. However, 10/15 minutes later it starts complaining about the connection not working because “device is unavailable”. Restarting the app updates the details but the next refresh fails again and the connection is broken.

Any thoughts?

**Comment by BBEHannes** [comment]
Addition;
It actually only works when I add the password again and restart the app. But only for a very brief period... like a minute or two.

**Comment by irritanterik** [comment]
Hi! What are your retry settings?

**Comment by BBEHannes** [comment]
Every 1 minute (default)

**Comment by Genghes** [comment]
Hi.
Just checked my app, and I have the same symptoms.
I can supply a new password and it validates it OK, but I get the 'No access to your Tesla account' error within seconds after restarting the app.

I have several other iOS apps polling the Tesla servers, so they are responding.

I'm at work now and do not have the ability to run the app on my lab Homey, but will do so as soon as i can to see it this provides more insight.

**Comment by BBEHannes** [comment]
This only started recently I believe. I use the app quite extensively and didn’t notice it until a week or two ago.

**Comment by Genghes** [comment]
Hmm.. Strange.
I ran the app in debug mode on my lab Homey, and set ut the connection to the car. Workes perfect..
Thinking this indicated a faulty install on the production Homey, I uninstalled the app, Reinstalled it and set ut the car from scratch. But ni sigar, On the production Homey is still failes moments after restarting the app.

**Comment by Genghes** [comment]
So.. After checking my logs, I see the problem started after a power outage about 13 days ago..
So i figured that might have something to do with it. So å initiated a reastart of Homey, and after the restart, waited for all my apps to start. And the Tesla app now seems stable again.

So please initiate a controlled restart from the app and wait 10 minutes.
Settings->General->Restart Homey

**Comment by BBEHannes** [comment]
Interesting finding! However; I have also done a graceful restart yesterday but without luck.. I’ll give it another shot

**Comment by Genghes** [comment]
Okey.. Spoke too soon.
The app on both production and my Lab Homey stopped.
But now i got the debug from the Lab Homey.
Looks like its loosing the API key?

@irritanterik Can you get something from this:

2020-04-29 21:13:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187629538,
  distanceTraveled: 0 }
2020-04-29 21:15:50 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187750212,
  distanceTraveled: 0 }
2020-04-29 21:17:50 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187870239,
  distanceTraveled: 0 }
error in Tesla.prototype.login Error: no_password
    at login (/lib/tesla.js:355:40)
    at Tesla.login (/lib/tesla.js:28:10)
    at checkTokenWithRequest.catch (/lib/tesla.js:62:76)
    at <anonymous>
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] invalid_user_pasword event triggered
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] Device unavailable due to invalid account / username / password
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] trackLocation Api error
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] trackController 1

**Comment by Genghes** [comment]
A bit more info.
It seems the token is not invalid. After restarting the app it connects using the same token as before.

**Comment by irritanterik** [comment]
Looks like the app thanks the token is no longer valid (could be timing issue with the expiration validation check) and tries to pull a new token (which fails since the app does not store the password - this change started all the losing connection issues).

**Comment by irritanterik** [comment]
So would be nice if you both could confirm the stored token is not expired nor invalidated and accepted by Tesla after an app restart

**Comment by BBEHannes** [comment]
Let me know how to gather the logs and I’m happy to verify.

To add info on how to make it work;

-Re-enter the password for the car
-wake up the car through the official Tesla app
-restart the Tesla homey app

It then is able to connect but only briefly.

**Comment by Genghes** [comment]
I can confirm the token is not expired or invalid. The app connects successfully using the same token after restarting but quickly runs into this issue of trying to log in.

**Comment by Genghes** [comment]
here is a complete log from start until failing then restarting and then failing again:
(I think i’ve anonymized everything, but if you see any sensitive data, please just delete this post)
`─────────────── Logging stdout & stderr ───────────────
2020-04-29 20:41:33 [log] [ManagerDrivers] [ev] Succesvol got grant in pairing
found a car: { id: ***********710344,
  vehicle_id: ******624,
  vin: '***********',
  display_name: 'Wikene',
  option_codes: 'AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0',
  color: null,
  tokens: [ '**********9b1802', '**********4cb2e9' ],
  state: 'online',
  in_service: false,
  id_s: '***********710343',
  calendar_enabled: true,
  api_version: 7,
  backseat_token: null,
  backseat_token_updated_at: null }
2020-04-29 20:41:38 [log] [ManagerDrivers] [ev] pairing: vehicle added { data: { id: '***********' },
  name: 'Wikene',
  icon: 'icon_x.svg',
  store:
   { grant:
      { access_token: '11ae**********d4ac',
        token_type: 'bearer',
        expires_in: 3888000,
        refresh_token: '7aae**********3695',
        created_at: 1588185693 },
     username: '*******@******.***' },
  settings: { password: '' } }
2020-04-29 20:41:38 [log] [ManagerDrivers] [ev] [0] ##### TESLA onInit ##### { Homey: '4.1.0', App: '2.1.2', Device: '***********' }
2020-04-29 20:41:38 [log] [ManagerDrivers] [ev] [0] settings { password: '',
  locationPolling: true,
  tripTracking: true,
  locationIntervalDriving: 30,
  locationIntervalParked: 120,
  batteryPolling: true,
  batteryInterval: 20,
  retriggerRestrictTime: 10,
  retriggerRestrictDistance: 1,
  tokenRetry: true,
  tokenRetryInterval: 1,
  apiAccess: false }
{ access_token: '11ae**********d4ac',
  token_type: 'bearer',
  expires_in: 3888000,
  refresh_token: '7aae**********3695',
  created_at: 1588185693 }
2020-04-29 20:41:40 [log] [ManagerDrivers] [ev] [0] trackController 1
2020-04-29 20:41:42 [log] [ManagerDrivers] [ev] [0] battery 57
2020-04-29 20:41:46 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588185706166,
  distanceTraveled: 0 }
2020-04-29 20:41:46 [log] [ManagerDrivers] [ev] [0] trackController setting { location: 120, battery: 1200 }
2020-04-29 20:43:47 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588185827909,
  distanceTraveled: 0 }
2020-04-29 20:45:48 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588185948438,
  distanceTraveled: 0 }
2020-04-29 20:48:47 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 20:48:47 [log] [ManagerDrivers] [ev] [0] trackLocation Api error
2020-04-29 20:49:48 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186188149,
  distanceTraveled: 0 }
2020-04-29 20:51:48 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186308583,
  distanceTraveled: 0 }
2020-04-29 20:53:47 [log] [TeslaApp] 20:53:47 Flow action set charge mode ***********
2020-04-29 20:53:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186429206,
  distanceTraveled: 0 }
2020-04-29 20:53:49 [log] [TeslaApp] 20:53:49 Flow action set charge limit ***********
2020-04-29 20:55:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186549208,
  distanceTraveled: 0 }
2020-04-29 20:57:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186669175,
  distanceTraveled: 0 }
2020-04-29 20:59:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186789349,
  distanceTraveled: 0 }
2020-04-29 21:01:48 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588186908326,
  distanceTraveled: 0 }
2020-04-29 21:01:48 [log] [ManagerDrivers] [ev] [0] battery 57
2020-04-29 21:03:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187029219,
  distanceTraveled: 0 }
2020-04-29 21:05:50 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187150204,
  distanceTraveled: 0 }
2020-04-29 21:07:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187269227,
  distanceTraveled: 0 }
2020-04-29 21:09:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187389397,
  distanceTraveled: 0 }
2020-04-29 21:11:59 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 21:11:59 [log] [ManagerDrivers] [ev] [0] trackLocation Api error
2020-04-29 21:13:49 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187629538,
  distanceTraveled: 0 }
2020-04-29 21:15:50 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187750212,
  distanceTraveled: 0 }
2020-04-29 21:17:50 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 32342971.3,
  timeSinceTrigger: 1588187870239,
  distanceTraveled: 0 }
error in Tesla.prototype.login Error: no_password
    at login (/lib/tesla.js:355:40)
    at Tesla.login (/lib/tesla.js:28:10)
    at checkTokenWithRequest.catch (/lib/tesla.js:62:76)
    at <anonymous>
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] invalid_user_pasword event triggered
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] Device unavailable due to invalid account / username / password
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] trackLocation Api error
2020-04-29 21:20:47 [log] [ManagerDrivers] [ev] [0] trackController 1



--- INFO: com.tesla has been killed ---
2020-04-29 22:51:44 [log] [ManagerDrivers] [ev] [0] ##### TESLA onInit ##### { Homey: '4.1.0', App: '2.1.2', Device: '**********' }
2020-04-29 22:51:44 [log] [ManagerDrivers] [ev] [0] settings { password: '',
  locationPolling: true,
  tripTracking: true,
  locationIntervalDriving: 30,
  locationIntervalParked: 120,
  batteryPolling: true,
  batteryInterval: 20,
  retriggerRestrictTime: 10,
  retriggerRestrictDistance: 1,
  tokenRetry: true,
  tokenRetryInterval: 1,
  apiAccess: false }
{ access_token: '11ae**********d4ac',
  token_type: 'bearer',
  expires_in: 3888000,
  refresh_token: '7aae**********3695',
  created_at: 1588185693 }
2020-04-29 22:51:46 [log] [ManagerDrivers] [ev] [0] trackController 1
2020-04-29 22:51:48 [log] [ManagerDrivers] [ev] [0] battery 57
2020-04-29 22:52:51 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 22:52:51 [log] [ManagerDrivers] [ev] [0] trackLocation { isMoving: false,
  distanceMovedSinceTrigger: 0,
  timeSinceTrigger: 1588193571597,
  distanceTraveled: 0 }
2020-04-29 22:52:51 [log] [ManagerDrivers] [ev] [0] trackController setting { location: 120, battery: 1200 }
error in Tesla.prototype.login Error: no_password
    at login (/lib/tesla.js:355:40)
    at Tesla.login (/lib/tesla.js:28:10)
    at checkTokenWithRequest.catch (/lib/tesla.js:62:76)
    at <anonymous>
2020-04-29 22:55:51 [log] [ManagerDrivers] [ev] [0] invalid_user_pasword event triggered
2020-04-29 22:55:51 [log] [ManagerDrivers] [ev] [0] Device unavailable due to invalid account / username / password
2020-04-29 22:55:51 [log] [ManagerDrivers] [ev] [0] error from Api, counting 1 to max 5
2020-04-29 22:55:51 [log] [ManagerDrivers] [ev] [0] trackLocation Api error
2020-04-29 22:55:51 [log] [ManagerDrivers] [ev] [0] trackController 1`

**Comment by BBEHannes** [comment]
Now it works for 3 hours straight. I genuinely do not know what triggers this behavior..

**Comment by kjettern** [comment]
I also have the problem with homey telling me to log in again. My tesla is in the garage and the 4g/lte is not that great down there. But the Tesla app manages to wake up the car and read everything, but homey fails. Not sure why. The trick to wake the car with the Tesla app and then restart the Homey app works and I will get a reading of battery etc

**Comment by Genghes** [comment]
This must be something triggered from a response from Tesla servers. Mine too has worked perfectly for two days now.

**Comment by BBEHannes** [comment]
I guess we can call this one resolved. Haven’t received any disconnect messages ever since so I take it this was a problem on the Tesla site. Gonna close this one for now.

Thanks everyone involved!
